var MIMES = [
	"video/mp4", 
	"video/3gpp", 
	"video/3gpp2", 
	"video/quicktime", 
	"audio/mp4", 
	"audio/mpeg", 
	"audio/3gpp", 
	"audio/3gpp2", 
	"audio/ogg", 
	"audio/aac", 
	"audio/opus", 
	"audio/wav", 
	"audio/webm", 
	"application/mp4", 
	"application/mp21", 
];
